export const SET_PLACES = 'SET_PLACES'
export const REMOVE_PLACE = 'REMOVE_PLACE';

// export const ADD_PLACE = 'ADD_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const PLACE_ADDED = 'PLACE_ADDED'
export const START_ADD_PLACE = 'START_ADD_PLACE'
// export const SELECT_PLACE = 'SELECT_PLACE'
// export const DESELECT_PLACE = 'DESELECT_PLACE'

export const TRY_AUTH = 'TRY_AUTH'

export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN'

export const SET_PRODUCTS = 'SET_PRODUCTS'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const PRODUCT_ADDED = 'PRODUCT_ADDED'
export const START_ADD_PRODUCT = 'START_ADD_PRODUCT'
export const START_UPDATE_PRODUCT = 'START_UPDATE_PRODUCT'
export const STOP_UPDATE_PRODUCT = 'STOP_UPDATE_PRODUCT'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const STOP_SEARCH_PRODUCT = 'STOP_SEARCH_PRODUCT'

export const SET_SHOPS = 'SET_SHOPS'
export const REMOVE_SHOP = 'REMOVE_SHOP'
export const DELETE_SHOP = 'DELETE_SHOP'
export const SHOP_ADDED = 'SHOP_ADDED'
export const START_ADD_SHOP = 'START_ADD_SHOP'
export const SEARCH_SHOP = 'SEARCH_SHOP'
export const STOP_SEARCH_SHOP = 'STOP_SEARCH_SHOP'

export const SET_USERS = 'SET_USERS'
export const REMOVE_USER = 'REMOVE_USER'
export const DELETE_USER = 'DELETE_USER'
export const USER_ADDED = 'USER_ADDED'
export const START_ADD_USER = 'START_ADD_USER'
export const SEARCH_USER = 'SEARCH_USER'
export const STOP_SEARCH_USER = 'STOP_SEARCH_USER'
